KJHH-1924 YTJ-servicen siirto
Opetushallitus/organisaatio pull request #211
Opened 2021-03-17 12:29 UTC by jakaarl

YTJ-service rajapinnoista organisaation alle. Sitä ei käytetä suoraan, vaan organisaatiopalvelun kautta.

2021-03-17 15:27 UTC, jollem requested changes

2021-03-17 15:27 UTC, jollem commented on ytj-client/ytj-webservice/src/main/java/fi/vm/sade/organisaatio/ytj/service/YTJServiceImpl.java
> +        }
String.join?

2021-03-17 15:27 UTC, jollem commented on ytj-client/ytj-webservice/src/main/java/fi/vm/sade/organisaatio/ytj/service/YtjDtoMapperHelper.java
> +        }
no onpas ruma..
voisi esim:
```
if ( isHurri(vastaus) ) {
  ytj.setSvNimi(vastaus.getToiminimi().getToiminimi());
} else {
  ytj.setNimi(safelyGetValueForThis(vastaus))
}
```
tai sitten siivota jotenkin muuten 

ja sama juttu metodin loppuun saakka

2021-03-17 15:27 UTC, jollem commented on ytj-client/ytj-webservice/src/main/java/fi/vm/sade/organisaatio/ytj/service/YtjDtoMapperHelper.java
> +    }
tämän voisi siistiä. esim kirjoittaa metodi joka etsii yhteystiedoista oikean tyyppisen ja sitten vaan 
yritys.setWww(findYhteystietoType(yhteystiedot, WWW))
yritys.setSahkoposti(findYhteystietoType(yhteystiedot, EMAIL))
jne...

metodihan olisi jotakuinkin (pseudo):
yhteystiedot.stream().filter(yhteystieto.type === type).findOne()

2021-03-17 15:27 UTC, jollem commented on ytj-client/ytj-webservice/src/main/java/fi/vm/sade/organisaatio/ytj/service/YtjDtoMapperHelper.java
> +    private String getKatuOsoite(YrityksenOsoiteV2DTO osoiteParam) {
äkkiseltään tämäkin näyttää melko rumalta. olen melko varma että tämän voisi tehdä kauniimminkin

2021-03-17 15:27 UTC, jollem commented on ytj-client/ytj-webservice/src/main/java/fi/vm/sade/organisaatio/ytj/service/YtjDtoMapperHelper.java
> +        dto.setYtunnus(ytjParam.getYTunnus() != null ? ytjParam.getYTunnus() : null);
C'moon.. seriously?..

2021-03-17 15:27 UTC, jollem commented on ytj-client/ytj-webservice/src/main/resources/cxf.xml
> +</beans>
newline

2021-03-17 18:04 UTC, jakaarl commented on ytj-client/README.md
> +  https://liitu.hard.ware.fi/confluence/display/PROG/Rajapintakuvauksia
Jaa, luulisin ettei ole toiminut vuosiin...

2021-03-18 07:24 UTC, jollem approved these changes
Toteutuksessa paikoin toivomisen varaa mutta tässähän koodia vain liikutellaan repositoryjen välillä

2021-03-18 09:27 UTC, merged