Organisaatio 2 ytj
Opetushallitus/organisaatio pull request #228
Opened 2021-05-11 13:21 UTC by jakaarl

2021-05-11 16:53 UTC, mkamka reviewed
Aikamoinen, mutta pitäis kyllä varmaan testata että toimiiko samalla tapaa kun vanha

2021-05-12 07:02 UTC, jollem requested changes
I would like to see some cleanup before merging this

2021-05-12 07:02 UTC, jollem commented on ytj-client/ytj-webservice/src/main/java/fi/vm/sade/organisaatio/ytj/service/YtjDtoMapperHelper.java
> +            return null;
sure that null is proper return value? might blow up later

2021-05-12 07:02 UTC, jollem commented on ytj-client/ytj-webservice/src/main/java/fi/vm/sade/organisaatio/ytj/service/YtjDtoMapperHelper.java
> +        dto.setNimi(ytjParam.getYritysnimi() != null ? ytjParam.getYritysnimi() : null);
ah, the classic...

2021-05-14 09:38 UTC, jollem approved these changes

2021-05-17 05:34 UTC, merged